# Install dependencies with full node 12 image that has node-gyp build support
FROM node:12 as builder

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm ci --only=prod

# Run with alpine image that has only runtime support
FROM node:12-alpine as runtime

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .
COPY src ./src

CMD [ "npm", "start" ]

